In [5]:
import fastf1
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

import matplotlib.pyplot as plt

# fastf1.Cache.enable_cache("cache")

ERROR! Session/line number was not unique in database. History logging moved to new session 67

In [6]:
YEAR = 2026

In [7]:
schedule = fastf1.get_event_schedule(YEAR)

schedule

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,2026-02-13,Pre-Season Testing,testing,Practice 1,2026-02-11 10:00:00+03:00,2026-02-11 07:00:00,...,Practice 3,2026-02-13 10:00:00+03:00,2026-02-13 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 2 2026,2026-02-20,Pre-Season Testing,testing,Practice 1,2026-02-18 10:00:00+03:00,2026-02-18 07:00:00,...,Practice 3,2026-02-20 10:00:00+03:00,2026-02-20 07:00:00,None,NaT,NaT,None,NaT,NaT,True
2,1,Australia,Melbourne,FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX ...,2026-03-08,Australian Grand Prix,conventional,Practice 1,2026-03-06 12:30:00+11:00,2026-03-06 01:30:00,...,Practice 3,2026-03-07 12:30:00+11:00,2026-03-07 01:30:00,Qualifying,2026-03-07 16:00:00+11:00,2026-03-07 05:00:00,Race,2026-03-08 15:00:00+11:00,2026-03-08 04:00:00,True
3,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2026,2026-03-15,Chinese Grand Prix,sprint_qualifying,Practice 1,2026-03-13 11:30:00+08:00,2026-03-13 03:30:00,...,Sprint,2026-03-14 11:00:00+08:00,2026-03-14 03:00:00,Qualifying,2026-03-14 15:00:00+08:00,2026-03-14 07:00:00,Race,2026-03-15 15:00:00+08:00,2026-03-15 07:00:00,True
4,3,Japan,Suzuka,FORMULA 1 ARAMCO JAPANESE GRAND PRIX 2026,2026-03-29,Japanese Grand Prix,conventional,Practice 1,2026-03-27 11:30:00+09:00,2026-03-27 02:30:00,...,Practice 3,2026-03-28 11:30:00+09:00,2026-03-28 02:30:00,Qualifying,2026-03-28 15:00:00+09:00,2026-03-28 06:00:00,Race,2026-03-29 14:00:00+09:00,2026-03-29 05:00:00,True
5,4,United States,Miami Gardens,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2026,2026-05-03,Miami Grand Prix,sprint_qualifying,Practice 1,2026-05-01 12:00:00-04:00,2026-05-01 16:00:00,...,Sprint,2026-05-02 12:00:00-04:00,2026-05-02 16:00:00,Qualifying,2026-05-02 16:00:00-04:00,2026-05-02 20:00:00,Race,2026-05-03 13:00:00-04:00,2026-05-03 17:00:00,True
6,5,Canada,Montréal,FORMULA 1 LENOVO GRAND PRIX DU CANADA 2026,2026-05-24,Canadian Grand Prix,sprint_qualifying,Practice 1,2026-05-22 12:30:00-04:00,2026-05-22 16:30:00,...,Sprint,2026-05-23 12:00:00-04:00,2026-05-23 16:00:00,Qualifying,2026-05-23 16:00:00-04:00,2026-05-23 20:00:00,Race,2026-05-24 16:00:00-04:00,2026-05-24 20:00:00,True
7,6,Monaco,Monte Carlo,FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026,2026-06-07,Monaco Grand Prix,conventional,Practice 1,2026-06-05 13:30:00+02:00,2026-06-05 11:30:00,...,Practice 3,2026-06-06 12:30:00+02:00,2026-06-06 10:30:00,Qualifying,2026-06-06 16:00:00+02:00,2026-06-06 14:00:00,Race,2026-06-07 15:00:00+02:00,2026-06-07 13:00:00,True
8,7,Spain,Barcelona,FORMULA 1 MSC CRUISES GRAN PREMIO DE BARCELONA...,2026-06-14,Barcelona Grand Prix,conventional,Practice 1,2026-06-12 13:30:00+02:00,2026-06-12 11:30:00,...,Practice 3,2026-06-13 12:30:00+02:00,2026-06-13 10:30:00,Qualifying,2026-06-13 16:00:00+02:00,2026-06-13 14:00:00,Race,2026-06-14 15:00:00+02:00,2026-06-14 13:00:00,True
9,8,Austria,Spielberg,FORMULA 1 LENOVO AUSTRIAN GRAND PRIX 2026,2026-06-28,Austrian Grand Prix,conventional,Practice 1,2026-06-26 13:30:00+02:00,2026-06-26 11:30:00,...,Practice 3,2026-06-27 12:30:00+02:00,2026-06-27 10:30:00,Qualifying,2026-06-27 16:00:00+02:00,2026-06-27 14:00:00,Race,2026-06-28 15:00:00+02:00,2026-06-28 13:00:00,True
10,9,United Kingdom,Silverstone,FORMULA 1 PIRELLI BRITISH GRAND PRIX 2026,2026-07-05,British Grand Prix,sprint_qualifying,Practice 1,2026-07-03 12:30:00+01:00,2026-07-03 11:30:00,...,Sprint,2026-07-04 12:00:00+01:00,2026-07-04 11:00:00,Qualifying,2026-07-04 16:00:00+01:00,2026-07-04 15:00:00,Race,2026-07-05 15:00:00+01:00,2026-07-05 14:00:00,True
11,10,Belgium,Spa-Francorchamps,FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2026,2026-07-19,Belgian Grand Prix,conventional,Practice 1,2026-07-17 13:30:00+02:00,2026-07-17 11:30:00,...,Practice 3,2026-07-18 12:30:00+02:00,2026-07-18 10:30:00,Qualifying,2026-07-18 16:00:00+02:00,2026-07-18 14:00:00,Race,2026-07-19 15:00:00+02:00,2026-07-19 13:00:00,True
12,11,Hungary,Budapest,FORMULA 1 AWS HUNGARIAN GRAND PRIX 2026,2026-07-26,Hungarian Grand Prix,conventional,Practice 1,2026-07-24 13:30:00+02:00,2026-07-24 11:30:00,...,Practice 3,2026-07-25 12:30:00+02:00,2026-07-25 10:30:00,Qualifying,2026-07-25 16:00:00+02:00,2026-07-25 14:00:00,Race,2026-07-26 15:00:00+02:00,2026-07-26 13:00:00,True
13,12,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2026,2026-08-23,Dutch Grand Prix,sprint_qualifying,Practice 1,2026-08-21 12:30:00+02:00,2026-08-21 10:30:00,...,Sprint,2026-08-22 12:00:00+02:00,2026-08-22 10:00:00,Qualifying,2026-08-22 16:00:00+02:00,2026-08-22 14:00:00,Race,2026-08-23 15:00:00+02:00,2026-08-23 13:00:00,True
14,13,Italy,Monza,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2026,2026-09-06,Italian Grand Prix,conventional,Practice 1,2026-09-04 12:30:00+02:00,2026-09-04 10:30:00,...,Practice 3,2026-09-05 12:30:00+02:00,2026-09-05 10:30:00,Qualifying,2026-09-05 16:00:00+02:00,2026-09-05 14:00:00,Race,2026-09-06 15:00:00+02:00,2026-09-06 13:00:00,True
15,14,Spain,Madrid,FORMULA 1 TAG HEUER GRAN PREMIO DE ESPAÑA 2026,2026-09-13,Spanish Grand Prix,conventional,Practice 1,2026-09-11 13:30:00+02:00,2026-09-11 11:30:00,...,Practice 3,2026-09-12 12:30:00+02:00,2026-09-12 10:30:00,Qualifying,2026-09-12 16:00:00+02:00,2026-09-12 14:00:00,Race,2026-09-13 15:00:00+02:00,2026-09-13 13:00:00,True
16,15,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2026-09-26,Azerbaijan Grand Prix,conventional,Practice 1,2026-09-24 12:30:00+04:00,2026-09-24 08:30:00,...,Practice 3,2026-09-25 12:30:00+04:00,2026-09-25 08:30:00,Qualifying,2026-09-25 16:00:00+04:00,2026-09-25 12:00:00,Race,2026-09-26 15:00:00+04:00,2026-09-26 11:00:00,True
17,16,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2026-10-11,Singapore Grand Prix,sprint_qualifying,Practice 1,2026-10-09 16:30:00+08:00,2026-10-09 08:30:00,...,Sprint,2026-10-10 17:00:00+08:00,2026-10-10 09:00:00,Qualifying,2026-10-10 21:00:00+08:00,2026-10-10 13:00:00,Race,2026-10-11 20:00:00+08:00,2026-10-11 12:00:00,True
18,17,United States,Austin,FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX...,2026-10-25,United States Grand Prix,conventional,Practice 1,2026-10-23 12:30:00-05:00,2026-10-23 17:30:00,...,Practice 3,2026-10-24 12:30:00-05:00,2026-10-24 17:30:00,Qualifying,2026-10-24 16:00:00-05:00,2026-10-24 21:00:00,Race,2026-10-25 15:00:00-05:00,2026-10-25 20:00:00,True
19,18,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026,2026-11-01,Mexico City Grand Prix,conventional,Practice 1,2026-10-30 12:30:00-06:00,2026-10-30 18:30:00,...,Practice 3,2026-10-31 11:30:00-06:00,2026-10-31 17:30:00,Qualifying,2026-10-31 15:00:00-06:00,2026-10-31 21:00:00,Race,2026-11-01 14:00:00-06:00,2026-11-01 20:00:00,True
20,19,Brazil,São Paulo,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,2026-11-08,São Paulo Grand Prix,conventional,Practice 1,2026-11-06 12:30:00-03:00,2026-11-06 15:30:00,...,Practice 3,2026-11-07 11:30:00-03:00,2026-11-07 14:30:00,Qualifying,2026-11-07 15:00:00-03:00,2026-11-07 18:00:00,Race,2026-11-08 14:00:00-03:00,2026-11-08 17:00:00,True
21,20,United States,Las Vegas,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026,2026-11-21,Las Vegas Grand Prix,conventional,Practice 1,2026-11-19 16:30:00-08:00,2026-11-20 00:30:00,...,Practice 3,2026-11-20 16:30:00-08:00,2026-11-21 00:30:00,Qualifying,2026-11-20 20:00:00-08:00,2026-11-21 04:00:00,Race,2026-11-21 20:00:00-08:00,2026-11-22 04:00:00,True
22,21,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026,2026-11-29,Qatar Grand Prix,conventional,Practice 1,2026-11-27 16:30:00+03:00,2026-11-27 13:30:00,...,Practice 3,2026-11-28 17:30:00+03:00,2026-11-28 14:30:00,Qualifying,2026-11-28 21:00:00+03:00,2026-11-28 18:00:00,Race,2026-11-29 19:00:00+03:00,2026-11-29 16:00:00,True
23,22,United Arab Emirates,Yas Marina,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2026-12-06,Abu Dhabi Grand Prix,conventional,Practice 1,2026-12-04 13:30:00+04:00,2026-12-04 09:30:00,...,Practice 3,2026-12-05 14:30:00+04:00,2026-12-05 10:30:00,Qualifying,2026-12-05 18:00:00+04:00,2026-12-05 14:00:00,Race,2026-12-06 17:00:00+04:00,2026-12-06 13:00:00,True

In [8]:
schedule.columns

Index(['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate',
       'EventName', 'EventFormat', 'Session1', 'Session1Date',
       'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc',
       'Session3', 'Session3Date', 'Session3DateUtc', 'Session4',
       'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date',
       'Session5DateUtc', 'F1ApiSupport'],
      dtype='object')

In [9]:
schedule.head()

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,2026-02-13,Pre-Season Testing,testing,Practice 1,2026-02-11 10:00:00+03:00,2026-02-11 07:00:00,...,Practice 3,2026-02-13 10:00:00+03:00,2026-02-13 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 2 2026,2026-02-20,Pre-Season Testing,testing,Practice 1,2026-02-18 10:00:00+03:00,2026-02-18 07:00:00,...,Practice 3,2026-02-20 10:00:00+03:00,2026-02-20 07:00:00,None,NaT,NaT,None,NaT,NaT,True
2,1,Australia,Melbourne,FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX ...,2026-03-08,Australian Grand Prix,conventional,Practice 1,2026-03-06 12:30:00+11:00,2026-03-06 01:30:00,...,Practice 3,2026-03-07 12:30:00+11:00,2026-03-07 01:30:00,Qualifying,2026-03-07 16:00:00+11:00,2026-03-07 05:00:00,Race,2026-03-08 15:00:00+11:00,2026-03-08 04:00:00,True
3,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2026,2026-03-15,Chinese Grand Prix,sprint_qualifying,Practice 1,2026-03-13 11:30:00+08:00,2026-03-13 03:30:00,...,Sprint,2026-03-14 11:00:00+08:00,2026-03-14 03:00:00,Qualifying,2026-03-14 15:00:00+08:00,2026-03-14 07:00:00,Race,2026-03-15 15:00:00+08:00,2026-03-15 07:00:00,True
4,3,Japan,Suzuka,FORMULA 1 ARAMCO JAPANESE GRAND PRIX 2026,2026-03-29,Japanese Grand Prix,conventional,Practice 1,2026-03-27 11:30:00+09:00,2026-03-27 02:30:00,...,Practice 3,2026-03-28 11:30:00+09:00,2026-03-28 02:30:00,Qualifying,2026-03-28 15:00:00+09:00,2026-03-28 06:00:00,Race,2026-03-29 14:00:00+09:00,2026-03-29 05:00:00,True

In [10]:
fig = px.scatter(
    schedule,
    x="RoundNumber",
    y="Country",
    hover_name="EventName",
    title=f"{YEAR} Formula 1 Calendar"
)

fig.show()

In [11]:
race = fastf1.get_session(YEAR, "Monaco", "R")
race.load()

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3']

In [12]:
race.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,1,1.0,NaT,NaT,NaT,0 days 02:23:31.243000,Finished,25.0,78.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,2.0,2,3.0,NaT,NaT,NaT,0 days 00:00:06.271000,Finished,18.0,78.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,3.0,3,9.0,NaT,NaT,NaT,0 days 00:00:20.369000,Finished,15.0,78.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:23.394000,Finished,12.0,78.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:24.261000,Finished,10.0,78.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,6.0,6,10.0,NaT,NaT,NaT,0 days 00:00:26.553000,Finished,8.0,78.0
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,7.0,7,15.0,NaT,NaT,NaT,0 days 00:00:29.010000,Finished,6.0,78.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,8.0,8,11.0,NaT,NaT,NaT,0 days 00:00:33.413000,Finished,4.0,78.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,9.0,9,17.0,NaT,NaT,NaT,0 days 00:00:37.140000,Finished,2.0,78.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,10.0,10,21.0,NaT,NaT,NaT,0 days 00:00:41.899000,Finished,1.0,78.0
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,11.0,11,16.0,NaT,NaT,NaT,0 days 00:00:42.748000,Finished,0.0,78.0
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,12.0,12,6.0,NaT,NaT,NaT,0 days 00:00:43.353000,Finished,0.0,78.0
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,13.0,13,13.0,NaT,NaT,NaT,0 days 00:00:44.102000,Finished,0.0,78.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,14.0,14,14.0,NaT,NaT,NaT,0 days 00:00:48.964000,Finished,0.0,78.0
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,15.0,15,18.0,NaT,NaT,NaT,0 days 00:00:49.153000,Finished,0.0,78.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,16.0,16,12.0,NaT,NaT,NaT,NaT,Retired,0.0,70.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,17.0,R,4.0,NaT,NaT,NaT,NaT,Retired,0.0,64.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,18.0,R,22.0,NaT,NaT,NaT,NaT,Retired,0.0,56.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,19.0,R,8.0,NaT,NaT,NaT,NaT,Retired,0.0,43.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,20.0,R,19.0,NaT,NaT,NaT,NaT,Retired,0.0,27.0
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,21.0,R,20.0,NaT,NaT,NaT,NaT,Retired,0.0,15.0
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,22.0,R,2.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0

In [13]:
TEAM_COLORS = {
    "Mercedes": "#00D2BE",
    "Ferrari": "#DC0000",
    "McLaren": "#FF8700",
    "Red Bull Racing": "#1E41FF",
    "Alpine": "#0090FF",
    "Racing Bulls": "#2B45FF",
    "Haas F1 Team": "#FFFFFF",
    "Williams": "#005AFF",
    "Audi": "#E30613",
    "Aston Martin": "#006F62",
    "Cadillac": "#0A0A0A"
}

TEAM_DRIVERS = {
    "Mercedes": ["RUS", "ANT"],
    "Ferrari": ["LEC", "HAM"],
    "McLaren": ["NOR", "PIA"],
    "Red Bull Racing": ["VER", "TSU"],
    "Alpine": ["COL", "GAS"],
    "Racing Bulls": ["HAD", "LAW"],
    "Haas F1 Team": ["OCO", "BEA"],
    "Williams": ["ALB", "SAI"],
    "Audi": ["HUL", "BOR"],
    "Aston Martin": ["ALO", "STR"],
    "Cadillac": ["PER", "ZHO"],
}

DRIVER_COLORS = {
    driver: TEAM_COLORS[team]
    for team, drivers in TEAM_DRIVERS.items()
    for driver in drivers
}

In [14]:
fig = px.bar(
    race.results,
    x="Abbreviation",
    y="Points",
    color="TeamName",
    color_discrete_map=TEAM_COLORS,
    title="Race Points"
)

fig.show()

In [15]:
race.results["Places Gained"] = (
    race.results["GridPosition"] - race.results["Position"]
)

fig = px.bar(
    race.results.sort_values("Places Gained"),
    x="Abbreviation",
    y="Places Gained",
    color="TeamName",
    color_discrete_map=TEAM_COLORS,
    title="Places Gained During Race"
)

fig.show()

In [16]:
all_results = []

for event in schedule["EventName"]:

    session = fastf1.get_session(YEAR, event, "R")
    session.load()

    df = session.results.copy()

    df["Race"] = event

    all_results.append(df)

events      WARNING 	Correcting user input 'Pre-Season Testing' to 'Singapore Grand Prix'
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
logger      WARNING 	Failed to load race control messages!
core           INFO 	Finished loading data for 0 drivers: []
events      WARNING 	Correcting user input 'Pre-Season Testing' to 'Singapore Grand Prix'
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
logger      WARNING 	Failed to load race control messages!
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 1)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 5)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
core        WARNING 	Driver 12 completed the race distance 00:00.022000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '87', '10', '30', '6', '55', '43', '27', '41', '77', '31', '11', '3', '14', '18', '81', '1', '5', '23']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '81', '16', '63', '1', '44', '10', '3', '30', '31', '27', '6', '5', '41', '55', '43', '11', '14', '77', '23', '18', '87']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 12 completed the race distance 00:00.027000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '1', '81', '63', '3', '44', '43', '16', '55', '23', '87', '5', '31', '41', '14', '11', '18', '77', '27', '30', '10', '6']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 41)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '3', '16', '6', '43', '30', '10', '55', '87', '81', '27', '5', '31', '18', '77', '11', '1', '63', '14', '23', '41']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3']
core           INFO 	Loading data for Barcelona Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['44', '63', '1', '3', '81', '6', '10', '30', '41', '43', '5', '55', '31', '11', '16', '12', '87', '23', '14', '27', '77', '18']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 63 completed the race distance 00:00.530000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '3', '12', '81', '44', '6', '1', '16', '30', '41', '5', '27', '10', '87', '43', '31', '23', '14', '18', '55', '11', '77']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
logger      WARNING 	Failed to load race control messages!
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
logger      WARNING 	Failed to load race control messages!
core           INFO 	Finished loading data for 0 drivers: []
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!

In [17]:
results_df = pd.concat(all_results)

In [18]:
points = (
    results_df
    .groupby(["Race", "Abbreviation"])["Points"]
    .sum()
    .reset_index()
)

fig = px.line(
    points,
    x="Race",
    y="Points",
    color="Abbreviation",
    color_discrete_map=DRIVER_COLORS,
    markers=True,
    title="Points Scored per Grand Prix"
)

fig.update_layout(
    xaxis_title="Grand Prix",
    yaxis_title="Points",
    legend_title="Driver",
    template="plotly_dark",
    hovermode="x unified"
)

fig.update_xaxes(tickangle=-45)

fig.show()

In [19]:
team_points = (
    results_df
    .groupby("TeamName")["Points"]
    .sum()
    .sort_values(ascending=False)
)

team_points = team_points.reset_index()

fig = px.bar(
    team_points,
    x="Points",
    y="TeamName",
    color="TeamName",
    color_discrete_map=TEAM_COLORS,
    orientation="h",
    title="Constructor Championship Points"
)

fig.update_layout(
    xaxis_title="Points",
    yaxis_title="Constructor",
    template="plotly_dark",
    showlegend=False
)

fig.update_yaxes(categoryorder="total ascending")

fig.show()

In [20]:
results_df["Places Gained"] = (
    results_df["GridPosition"] - results_df["Position"]
)

places = (
    results_df
    .groupby("Abbreviation", as_index=False)["Places Gained"]
    .mean()
    .sort_values("Places Gained", ascending=False)
)

In [21]:
podiums = (
    results_df[results_df["Position"] <= 3]
    .groupby("Abbreviation", as_index=False)
    .size()
    .rename(columns={"size": "Podiums"})
    .sort_values("Podiums", ascending=False)
)

fig = px.bar(
    podiums,
    x="Abbreviation",
    y="Podiums",
    color="Abbreviation",
    color_discrete_map=DRIVER_COLORS,
    title="Podiums"
)

fig.update_layout(
    template="plotly_dark",
    showlegend=False
)

fig.show()

In [22]:
dnfs = (
    results_df[results_df["Status"] != "Finished"]
    .groupby("Abbreviation", as_index=False)
    .size()
    .rename(columns={"size": "DNFs"})
    .sort_values("DNFs", ascending=False)
)

fig = px.bar(
    dnfs,
    x="Abbreviation",
    y="DNFs",
    color="Abbreviation",
    color_discrete_map=DRIVER_COLORS,
    title="DNFs"
)

fig.update_layout(
    template="plotly_dark",
    showlegend=False
)

fig.show()

In [23]:
comparison = (
    results_df
    .groupby("Abbreviation", as_index=False)
    .agg({
        "GridPosition": "mean",
        "Position": "mean"
    })
)

fig = px.scatter(
    comparison,
    x="GridPosition",
    y="Position",
    color="Abbreviation",
    color_discrete_map=DRIVER_COLORS,
    text="Abbreviation",
    title="Qualifying vs Race Performance"
)

fig.update_traces(textposition="top center")

fig.update_layout(
    template="plotly_dark",
    xaxis_title="Average Grid Position",
    yaxis_title="Average Finishing Position",
    showlegend=False
)

fig.update_xaxes(autorange="reversed")
fig.update_yaxes(autorange="reversed")

fig.show()