### Qualification

In [1]:
import pandas as pd

df = pd.read_csv('weekend_data/qualifying.csv')
df

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
0,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,NaN,NaN,0 days 00:01:13.599000,0 days 00:01:12.704000,0 days 00:01:12.051000,NaN,NaN,NaN,NaN
1,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,2.0,NaN,NaN,0 days 00:01:13.490000,0 days 00:01:12.499000,0 days 00:01:12.094000,NaN,NaN,NaN,NaN
2,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,NaN,NaN,0 days 00:01:13.777000,0 days 00:01:12.934000,0 days 00:01:12.279000,NaN,NaN,NaN,NaN
3,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,NaN,NaN,0 days 00:01:13.293000,0 days 00:01:12.774000,0 days 00:01:12.351000,NaN,NaN,NaN,NaN
4,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,5.0,NaN,NaN,0 days 00:01:14.408000,0 days 00:01:12.722000,0 days 00:01:12.434000,NaN,NaN,NaN,NaN
5,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,6.0,NaN,NaN,0 days 00:01:14.214000,0 days 00:01:13.238000,0 days 00:01:12.445000,NaN,NaN,NaN,NaN
6,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,7.0,NaN,NaN,0 days 00:01:14.159000,0 days 00:01:12.983000,0 days 00:01:12.624000,NaN,NaN,NaN,NaN
7,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,8.0,NaN,NaN,0 days 00:01:13.630000,0 days 00:01:12.919000,0 days 00:01:12.765000,NaN,NaN,NaN,NaN
8,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,9.0,NaN,NaN,0 days 00:01:14.469000,0 days 00:01:13.762000,0 days 00:01:13.226000,NaN,NaN,NaN,NaN
9,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,10.0,NaN,NaN,0 days 00:01:14.498000,0 days 00:01:13.471000,0 days 00:01:13.412000,NaN,NaN,NaN,NaN
10,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,11.0,NaN,NaN,0 days 00:01:14.321000,0 days 00:01:13.787000,NaN,NaN,NaN,NaN,NaN
11,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,12.0,NaN,NaN,0 days 00:01:14.348000,0 days 00:01:13.815000,NaN,NaN,NaN,NaN,NaN
12,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,13.0,NaN,NaN,0 days 00:01:13.923000,0 days 00:01:13.902000,NaN,NaN,NaN,NaN,NaN
13,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,14.0,NaN,NaN,0 days 00:01:14.573000,0 days 00:01:13.995000,NaN,NaN,NaN,NaN,NaN
14,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,15.0,NaN,NaN,0 days 00:01:14.685000,0 days 00:01:14.248000,NaN,NaN,NaN,NaN,NaN
15,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,16.0,NaN,NaN,0 days 00:01:14.683000,NaN,NaN,NaN,NaN,NaN,NaN
16,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,17.0,NaN,NaN,0 days 00:01:14.722000,NaN,NaN,NaN,NaN,NaN,NaN
17,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,18.0,NaN,NaN,0 days 00:01:14.747000,NaN,NaN,NaN,NaN,NaN,NaN
18,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,19.0,NaN,NaN,0 days 00:01:14.814000,NaN,NaN,NaN,NaN,NaN,NaN
19,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,20.0,NaN,NaN,0 days 00:01:15.283000,NaN,NaN,NaN,NaN,NaN,NaN
20,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,21.0,NaN,NaN,0 days 00:01:15.349000,NaN,NaN,NaN,NaN,NaN,NaN
21,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,22.0,NaN,NaN,0 days 00:01:16.061000,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df = df.drop(columns=['BroadcastName','DriverId','TeamColor','TeamId','FirstName','LastName','FullName','HeadshotUrl','CountryCode','ClassifiedPosition','GridPosition','Time','Status','Points','Laps'], errors='ignore')

df

,DriverNumber,Abbreviation,TeamName,Position,Q1,Q2,Q3
0,12,ANT,Mercedes,1.0,0 days 00:01:13.599000,0 days 00:01:12.704000,0 days 00:01:12.051000
1,3,VER,Red Bull Racing,2.0,0 days 00:01:13.490000,0 days 00:01:12.499000,0 days 00:01:12.094000
2,44,HAM,Ferrari,3.0,0 days 00:01:13.777000,0 days 00:01:12.934000,0 days 00:01:12.279000
3,16,LEC,Ferrari,4.0,0 days 00:01:13.293000,0 days 00:01:12.774000,0 days 00:01:12.351000
4,6,HAD,Red Bull Racing,5.0,0 days 00:01:14.408000,0 days 00:01:12.722000,0 days 00:01:12.434000
5,63,RUS,Mercedes,6.0,0 days 00:01:14.214000,0 days 00:01:13.238000,0 days 00:01:12.445000
6,81,PIA,McLaren,7.0,0 days 00:01:14.159000,0 days 00:01:12.983000,0 days 00:01:12.624000
7,1,NOR,McLaren,8.0,0 days 00:01:13.630000,0 days 00:01:12.919000,0 days 00:01:12.765000
8,10,GAS,Alpine,9.0,0 days 00:01:14.469000,0 days 00:01:13.762000,0 days 00:01:13.226000
9,30,LAW,Racing Bulls,10.0,0 days 00:01:14.498000,0 days 00:01:13.471000,0 days 00:01:13.412000
10,23,ALB,Williams,11.0,0 days 00:01:14.321000,0 days 00:01:13.787000,NaN
11,55,SAI,Williams,12.0,0 days 00:01:14.348000,0 days 00:01:13.815000,NaN
12,27,HUL,Audi,13.0,0 days 00:01:13.923000,0 days 00:01:13.902000,NaN
13,43,COL,Alpine,14.0,0 days 00:01:14.573000,0 days 00:01:13.995000,NaN
14,41,LIN,Racing Bulls,15.0,0 days 00:01:14.685000,0 days 00:01:14.248000,NaN
15,5,BOR,Audi,16.0,0 days 00:01:14.683000,NaN,NaN
16,31,OCO,Haas F1 Team,17.0,0 days 00:01:14.722000,NaN,NaN
17,11,PER,Cadillac,18.0,0 days 00:01:14.747000,NaN,NaN
18,87,BEA,Haas F1 Team,19.0,0 days 00:01:14.814000,NaN,NaN
19,77,BOT,Cadillac,20.0,0 days 00:01:15.283000,NaN,NaN
20,14,ALO,Aston Martin,21.0,0 days 00:01:15.349000,NaN,NaN
21,18,STR,Aston Martin,22.0,0 days 00:01:16.061000,NaN,NaN

In [3]:
q1_td = pd.to_timedelta(df['Q1'], errors='coerce')
top7 = df.loc[q1_td.nlargest(7).index]
print(f"Drivers who finished their qualifying on Q1: {', '.join(top7['Abbreviation'])}")

Drivers who finished their qualifying on Q1: STR, ALO, BOT, BEA, PER, OCO, LIN

This seems interesting LIN has worse time than BOR, yet LIN goes to Q2, did BOR DNF?

In [4]:
q2_td = pd.to_timedelta(df['Q2'], errors='coerce')
top5 = df.loc[q2_td.nlargest(5).index]
print(f"Drivers who finished their qualifying on Q2: {', '.join(top5['Abbreviation'])}")

Drivers who finished their qualifying on Q2: LIN, COL, HUL, SAI, ALB

In [5]:
remaining_q1 = df['Abbreviation'].head(10)
print(", ".join(remaining_q1))

ANT, VER, HAM, LEC, HAD, RUS, PIA, NOR, GAS, LAW

In [6]:
fastest_idx = q1_td.idxmin()
slowest_idx = q1_td.idxmax()

fastest_driver = df.loc[fastest_idx, 'Abbreviation']
slowest_driver = df.loc[slowest_idx, 'Abbreviation']
best_time = q1_td.min()
worst_time = q1_td.max()
gap = worst_time - best_time

print(f"Fastest Q1 time: {fastest_driver} - {best_time}")
print(f"Slowest Q1 time: {slowest_driver} - {worst_time}")
print(f"Gap between fastest and slowest: {gap.total_seconds():.3f} seconds")
print(f"On a track as tight as Monaco, a gap of {gap.total_seconds():.3f}s over a ~72s lap is huge")

Fastest Q1 time: LEC - 0 days 00:01:13.293000
Slowest Q1 time: STR - 0 days 00:01:16.061000
Gap between fastest and slowest: 2.768 seconds
On a track as tight as Monaco, a gap of 2.768s over a ~72s lap is huge

In [7]:
q3_td = pd.to_timedelta(df['Q3'], errors='coerce')
fastest_idx_q3 = q3_td.idxmin()
slowest_idx_q3 = q3_td.idxmax()

fastest_driver_q3 = df.loc[fastest_idx_q3, 'Abbreviation']
slowest_driver_q3 = df.loc[slowest_idx_q3, 'Abbreviation']
best_q3_time = q3_td.min()
worst_q3_time = q3_td.max()
gap_q3 = worst_q3_time - best_q3_time

print(f"Fastest Q3 time: {fastest_driver_q3} - {best_q3_time}")
print(f"Slowest Q3 time: {slowest_driver_q3} - {worst_q3_time}")
print(f"Gap between fastest and slowest in Q3: {gap_q3.total_seconds():.3f} seconds")
slowest_driverQ3 = df.loc[slowest_idx, 'Abbreviation']

print("")

print(f"Fastest Q1 time: {fastest_driver} - {best_time}")
print(f"Slowest Q3 time: {slowest_driverQ3} - {worst_time}")
print(f"Gap between fastest and slowest: {gap.total_seconds():.3f} seconds")

Fastest Q3 time: ANT - 0 days 00:01:12.051000
Slowest Q3 time: LAW - 0 days 00:01:13.412000
Gap between fastest and slowest in Q3: 1.361 seconds

Fastest Q1 time: LEC - 0 days 00:01:13.293000
Slowest Q3 time: STR - 0 days 00:01:16.061000
Gap between fastest and slowest: 2.768 seconds

In [8]:
improvement = pd.DataFrame({
    'Abbreviation': df['Abbreviation'],
    'Q1': q1_td.dt.total_seconds(),
    'Q2': q2_td.dt.total_seconds(),
    'Q3': q3_td.dt.total_seconds(),
})

# Positive = got faster (improved), negative = got slower
improvement['Q1_to_Q2'] = improvement['Q1'] - improvement['Q2']
improvement['Q2_to_Q3'] = improvement['Q2'] - improvement['Q3']

q1_to_q2 = improvement.dropna(subset=['Q1_to_Q2']).sort_values('Q1_to_Q2', ascending=False)
q2_to_q3 = improvement.dropna(subset=['Q2_to_Q3']).sort_values('Q2_to_Q3', ascending=False)

print("Q1 -> Q2 improvement (seconds gained), only drivers who advanced:")
print(q1_to_q2[['Abbreviation', 'Q1', 'Q2', 'Q1_to_Q2']].to_string(index=False))

print("\nQ2 -> Q3 improvement (seconds gained), only drivers who advanced:")
print(q2_to_q3[['Abbreviation', 'Q2', 'Q3', 'Q2_to_Q3']].to_string(index=False))

biggest_q1q2 = q1_to_q2.iloc[0]
biggest_q2q3 = q2_to_q3.iloc[0]
print(f"\nBiggest Q1->Q2 gain: {biggest_q1q2['Abbreviation']} found {biggest_q1q2['Q1_to_Q2']:.3f}s")
print(f"Biggest Q2->Q3 gain: {biggest_q2q3['Abbreviation']} found {biggest_q2q3['Q2_to_Q3']:.3f}s")

Q1 -> Q2 improvement (seconds gained), only drivers who advanced:
Abbreviation     Q1     Q2  Q1_to_Q2
         HAD 74.408 72.722     1.686
         PIA 74.159 72.983     1.176
         LAW 74.498 73.471     1.027
         VER 73.490 72.499     0.991
         RUS 74.214 73.238     0.976
         ANT 73.599 72.704     0.895
         HAM 73.777 72.934     0.843
         NOR 73.630 72.919     0.711
         GAS 74.469 73.762     0.707
         COL 74.573 73.995     0.578
         ALB 74.321 73.787     0.534
         SAI 74.348 73.815     0.533
         LEC 73.293 72.774     0.519
         LIN 74.685 74.248     0.437
         HUL 73.923 73.902     0.021

Q2 -> Q3 improvement (seconds gained), only drivers who advanced:
Abbreviation     Q2     Q3  Q2_to_Q3
         RUS 73.238 72.445     0.793
         HAM 72.934 72.279     0.655
         ANT 72.704 72.051     0.653
         GAS 73.762 73.226     0.536
         LEC 72.774 72.351     0.423
         VER 72.499 72.094     0.405
         PIA 72.983 72.624     0.359
         HAD 72.722 72.434     0.288
         NOR 72.919 72.765     0.154
         LAW 73.471 73.412     0.059

Biggest Q1->Q2 gain: HAD found 1.686s
Biggest Q2->Q3 gain: RUS found 0.793s